from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
import io


def _base_doc(buffer):
    return SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=2*cm, leftMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm
    )


def generate_predictions_pdf(predictions_text: str, subject: str) -> bytes:
    buffer = io.BytesIO()
    doc = _base_doc(buffer)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("title", parent=styles["Title"],
        fontSize=18, textColor=colors.HexColor("#5a4fcf"),
        spaceAfter=6, alignment=TA_CENTER)
    sub_style = ParagraphStyle("sub", parent=styles["Normal"],
        fontSize=10, textColor=colors.grey, alignment=TA_CENTER, spaceAfter=20)
    h2_style = ParagraphStyle("h2", parent=styles["Heading2"],
        fontSize=13, textColor=colors.HexColor("#5a4fcf"), spaceBefore=14, spaceAfter=6)
    body_style = ParagraphStyle("body", parent=styles["Normal"],
        fontSize=10, leading=16, spaceAfter=4)

    story = [
        Paragraph("ExamLens AI — Predicted Questions", title_style),
        Paragraph(f"Subject: {subject} | Generated by ExamLens AI", sub_style),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#5a4fcf")),
        Spacer(1, 12),
    ]

    for line in predictions_text.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 6))
        elif line.startswith("## ") or line.startswith("# "):
            story.append(Paragraph(line.replace("#", "").strip(), h2_style))
        else:
            clean = line.replace("**", "").replace("*", "")
            story.append(Paragraph(clean, body_style))

    doc.build(story)
    return buffer.getvalue()


def generate_roadmap_pdf(roadmap_text: str, subject: str) -> bytes:
    buffer = io.BytesIO()
    doc = _base_doc(buffer)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("title", parent=styles["Title"],
        fontSize=18, textColor=colors.HexColor("#5a4fcf"),
        spaceAfter=6, alignment=TA_CENTER)
    sub_style = ParagraphStyle("sub", parent=styles["Normal"],
        fontSize=10, textColor=colors.grey, alignment=TA_CENTER, spaceAfter=20)
    h2_style = ParagraphStyle("h2", parent=styles["Heading2"],
        fontSize=13, textColor=colors.HexColor("#5a4fcf"), spaceBefore=14, spaceAfter=6)
    body_style = ParagraphStyle("body", parent=styles["Normal"],
        fontSize=10, leading=16, spaceAfter=4)
    day_style = ParagraphStyle("day", parent=styles["Normal"],
        fontSize=11, leading=16, spaceAfter=4,
        textColor=colors.HexColor("#1a1a3a"), fontName="Helvetica-Bold")

    story = [
        Paragraph("ExamLens AI — 7-Day Study Roadmap", title_style),
        Paragraph(f"Subject: {subject} | Generated by ExamLens AI", sub_style),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#5a4fcf")),
        Spacer(1, 12),
    ]

    for line in roadmap_text.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 6))
        elif line.startswith("## ") or line.startswith("# "):
            story.append(Paragraph(line.replace("#", "").strip(), h2_style))
        elif line.lower().startswith("day "):
            story.append(Paragraph(line.replace("**", ""), day_style))
        else:
            clean = line.replace("**", "").replace("*", "").replace("-", "•")
            story.append(Paragraph(clean, body_style))

    doc.build(story)
    return buffer.getvalue()


def generate_mcq_pdf(mcq_text: str, topic: str) -> bytes:
    buffer = io.BytesIO()
    doc = _base_doc(buffer)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("title", parent=styles["Title"],
        fontSize=18, textColor=colors.HexColor("#5a4fcf"),
        spaceAfter=6, alignment=TA_CENTER)
    sub_style = ParagraphStyle("sub", parent=styles["Normal"],
        fontSize=10, textColor=colors.grey, alignment=TA_CENTER, spaceAfter=20)
    q_style = ParagraphStyle("q", parent=styles["Normal"],
        fontSize=11, leading=16, spaceAfter=4, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#1a1a3a"))
    opt_style = ParagraphStyle("opt", parent=styles["Normal"],
        fontSize=10, leading=15, spaceAfter=2, leftIndent=15)
    ans_style = ParagraphStyle("ans", parent=styles["Normal"],
        fontSize=10, leading=15, spaceAfter=2, leftIndent=15,
        textColor=colors.HexColor("#059669"), fontName="Helvetica-Bold")
    tip_style = ParagraphStyle("tip", parent=styles["Normal"],
        fontSize=9, leading=14, spaceAfter=8, leftIndent=15,
        textColor=colors.HexColor("#5a4fcf"))

    story = [
        Paragraph(f"ExamLens AI — MCQ Practice: {topic}", title_style),
        Paragraph("Generated by ExamLens AI | AKTU/HBTU Style", sub_style),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#5a4fcf")),
        Spacer(1, 12),
    ]

    for line in mcq_text.split("\n"):
        line = line.strip()
        if not line or line == "---":
            story.append(Spacer(1, 10))
        elif line.startswith("Q") and line[1].isdigit():
            story.append(Paragraph(line, q_style))
        elif line.startswith(("A)", "B)", "C)", "D)")):
            story.append(Paragraph(line, opt_style))
        elif line.startswith("Answer:"):
            story.append(Paragraph("✓ " + line, ans_style))
        elif line.startswith("Tip:"):
            story.append(Paragraph("💡 " + line, tip_style))
        else:
            story.append(Paragraph(line, opt_style))

    doc.build(story)
    return buffer.getvalue()


def generate_extracted_questions_pdf(questions_text: str, subject: str) -> bytes:
    buffer = io.BytesIO()
    doc = _base_doc(buffer)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("title", parent=styles["Title"],
        fontSize=18, textColor=colors.HexColor("#5a4fcf"),
        spaceAfter=6, alignment=TA_CENTER)
    sub_style = ParagraphStyle("sub", parent=styles["Normal"],
        fontSize=10, textColor=colors.grey, alignment=TA_CENTER, spaceAfter=20)
    unit_style = ParagraphStyle("unit", parent=styles["Heading2"],
        fontSize=12, textColor=colors.HexColor("#5a4fcf"), spaceBefore=12, spaceAfter=4)
    q_style = ParagraphStyle("q", parent=styles["Normal"],
        fontSize=10, leading=15, spaceAfter=4, leftIndent=10)

    story = [
        Paragraph(f"ExamLens AI — Extracted Questions", title_style),
        Paragraph(f"Subject: {subject} | Generated by ExamLens AI", sub_style),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#5a4fcf")),
        Spacer(1, 12),
    ]

    for line in questions_text.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 4))
        elif line.upper().startswith("UNIT") or line.startswith("====="):
            story.append(Paragraph(line.replace("=", "").strip(), unit_style))
        else:
            story.append(Paragraph(line, q_style))

    doc.build(story)
    return buffer.getvalue()
